version: '3'
services:
  backend:
#    build: .
#    build:
#      context: .
#      dockerfile: builders/Nginx
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
#      - "9000:9000"
#    links:
#      - redis:redis
#      - percona:percona
#      - mailhog:mailhog
    # - mysql:mysql
    # - gearman:gearman
    # - solr:solr
    # - mongo:mongo
    # - memcached:memcached
    # - elasticsearch:elasticsearch
    # - rabbitmq:rabbitmq
    environment:
      XDEBUG_CONFIG: remote_host=127.0.0.1 remote_connect_back=0
    restart: always
    volumes:
      - ./www:/var/www/html/
      - ./conf/nginx/ssl:/etc/ssl/local/
      - ./conf/nginx/sites:/etc/nginx/conf.d
      - ./storage/logs/supervisor:/var/log/supervisor
      - ./storage/logs/nginx:/var/log/nginx

  php:
    build: .
    build:
      context: .
      dockerfile: builders/PHP/5.6-fpm
    container_name: php56
    restart: always
    volumes:
      - ./www:/var/www/html
      - ./conf/php/mods-available:/usr/local/etc/php/conf.d

  percona:
    image: percona
    container_name: percona
    ports:
      - "3306:3306"
    volumes:
      - ./storage/percona/data:/var/lib/mysql
      - ./storage/dumps:/var/dumps
      - ./conf/percona/conf.d:/etc/mysql/percona-server.conf.d

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mailhog:
     image: mailhog/mailhog
     container_name: mailhog
     ports:
       - "1025:1025"
       - "8025:8025"

  #mysql:
  #  image: mysql
  #  container_name: mysql
  #  ports:
  #    - "3307:3306"
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #  volumes:
  #    - ./storage/mysql/data:/var/lib/mysql
  #    - ./storage/dumps:/var/dumps

  #varnish:
  #  build: .
  #  build:
  #    context: .
  #    dockerfile: builders/VarnishCache
  #  container_name: varnish
  #  ports:
  #    - "8080:80"
  #  links:
  #    - backend:backend
  #  volumes:
  #    - ./conf/varnish/etc:/etc/varnish

  #gearman:
  #  build: .
  #  dockerfile: builders/Gearman
  #  container_name: gearman
  #  ports:
  #     - "4730:4730"

  #solr:
  #  image: solr
  #  container_name: solr
  #  ports:
  #    - "27017:27017"

  #mongo:
  #  image: mongo
  #  container_name: mongo
  #  ports:
  #    - "27017:27017"

  #memcached:
  #  image: memcached
  #  container_name: memcached
  #  ports:
  #    - "11211:11211"

  #elasticsearch:
  #  image: elasticsearch
  #  container_name: elasticsearch
  #  ports:
  #    - "9200:9200"
  #    - "9300:9300"

  #rabbitmq:
  #  image: rabbitmq:3.6.1-management
  #  container_name: rabbitmq
  #  ports:
  #    - "15672:15672"
  #    - "5672:5672"
